---
title: Ozveny
subtitle: IF rulez 2021
author: Nina Wančová et. al
subject: "Ozveny"
keywords: [books]
language: cs-CZ
lof: false
lof-own-page: false
toc-own-page: false
toc-title: Obsah
titlepage: false
papersize: a4
colorlinks: true
book: true
---
