---
title: Ozvěny informačních pondělků 20-21
subtitle: Informace - Technologie - Trendy - Diskuse
author: Nina Wančová et. al
subject: Ozvěny informačních pondělků
keywords: [books]
language: cs-CZ
lof: false
lof-own-page: false
toc-own-page: false
toc-title: Obsah
titlepage: false
papersize: a4
colorlinks: true
book: true
documentclass: book
---
